[package]
authors = ["James Munns <james.munns@ferrous-systems.com>"]
name = "bringup-001"
edition = "2018"
version = "0.1.0"

[workspace]
members = ["testsuite"]

[dependencies]
cortex-m = "0.6.4"
cortex-m-rt = "0.6.13"
ws2812-spi = "0.3"
smart-leds = "0.3.0"
embedded-hal = "0.2.4"
nb = "1.0.0"
stm32-usbd = { version = "0.5.1", features = ["ram_access_2x16"] }
usb-device = "0.2.7"
usbd-serial = "0.1.1"
cortex-m-rtic = "0.5.5"
rand_chacha = { version = "0.2.2", default-features = false }
rand = { version = "0.7.3", default-features = false }

[dependencies.bbqueue]
path = "../../bbqueue/core"
features = ["defmt"]

[dependencies.defmt]
git = "https://github.com/knurling-rs/defmt"
# branch = "main"
rev = "28c1afb4d3bad747ef47737a83f5c8b13928cb8a"

[dependencies.defmt-rtt]
git = "https://github.com/knurling-rs/defmt"
# branch = "main"
rev = "28c1afb4d3bad747ef47737a83f5c8b13928cb8a"

[dependencies.panic-probe]
git = "https://github.com/knurling-rs/probe-run"
# branch = "main"
rev = "056d958a"

[dependencies.stm32f4xx-hal]
path = "../../stm32f4xx-hal"
features = ["stm32f411", "rt", "usb_fs"]

[features]
# set logging levels here
default = [
  "defmt-default",
  # "dependency-a/defmt-trace",
]

# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 3 # <-
overflow-checks = true # <-

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3 # <-
overflow-checks = false # <-

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
